name: PolkadexTEE-worker CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-polkadexTEE:
    runs-on: ubuntu-latest
    container: "scssubstratee/substratee_dev:1804-2.12-1.1.3-001"
    steps:
      - uses: actions/checkout@v2
      - name: Build Project
        run: make