name: PolkadexTEE-worker CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-polkadexTEE:
    strategy:
      matrix:
        runs-on:
          - self-hosted
        image:
          - "scssubstratee/substratee_dev:1804-2.12-1.1.3-001"
    runs-on: ${{ matrix.runs-on }}
    container:
      image: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
          default: true
          components: rustfmt, clippy
      - name: Build Project
        run: make